### ISSUE TITLE
wikipedia changed their layout

### ISSUE THREAD

**Issue by sesucc** [Metastem/wikiless#6]
resulting in the wikiless layout looking kinda wonky
![image](https://user-images.githubusercontent.com/121158598/213900139-49a1bd10-6c8d-4365-b675-effe1a396f63.png)

**Comment by aaferrari** [comment]
In fact it only affects English Wikipedia. In other language versions that did not adopt the change (such as [Spanish Wikipedia](https://wikiless.org/wiki/?lang=es)) it is still seen normally. 

Currently there is [this proposal](https://en.wikipedia.org/wiki/Wikipedia:Requests_for_comment/Rollback_of_Vector_2022) to see if they go back to the previous skin (at the time of writing this comment, the results are 128 in favor, 79 opposed and 8 neutral) but if an urgent patch is needed and/or if in the end they stay with Vector 2022, you can continue parsing the content in this way: https://en.wikipedia.org/wiki/Some_article?useskin=vector which helps to maintain compatibility, although instead of `vector` you can also use `monobook`, `timeless` or `minerva` (see [this](https://www.mediawiki.org/wiki/Bundled_extensions_and_skins#Skins) for more information about the skins).

**Comment by RaptaG** [comment]
This issue is still present on my end, on Greek and English language so far.

**Comment by mada199122** [comment]
still present even for me...
You should think to reopen the issue.
Thanks

**Comment by Metastem** [comment]
> still present even for me... You should think to reopen the issue. Thanks

I think its fixed now

**Comment by liam-h** [comment]
It is not in fact fixed in English, you still need to add the useskin parameter in orde to get it to render right.

**Comment by f34rther34per** [comment]
I have an update on this. On my private instance I am still using version 0.1.0 instead of the latest 0.1.1. When I used the utils.js with @Metastem's changes, wikipedia displays perfectly fine. Perhaps version 0.1.0 should be used as a basis moving forward, at least so long as the new vector interface is the default. 
![image](https://user-images.githubusercontent.com/103328548/220657762-3b22c832-87dd-44ab-ba24-e4fa2e4ab13e.png)

**Comment by xbdmHQ** [comment]
@Metastem close this

**Comment by RaptaG** [comment]
Um, they shouldn't, https://wikiless.org is still broken, other instances are not

**Comment by xbdmHQ** [comment]
> Um, they shouldn't, https://wikiless.org is still broken, other instances are not

Hey, sorry that i got back late. Those instances are lazy and are not updating frequently. The source code and many others with up to date wikiless is fixed! Make sure to choose the right up to date one like the official: https://wikiless.whateveritworks.org

**Comment by RaptaG** [comment]
Thanks for the status update! The original instance looked cool, but it's fine..
